export const ballRespond = {
  uk: [
    "Так - давайте зробимо це! Життя - це пригода!",
    "Ні - може, краще залишити це для іншого часу.",
    "Так - чому б і ні? Лише жартую, давайте ризикнемо!",
    "Ні - здається, це може призвести до веселих неприємностей.",
    "Так - гарний варіант, адже життя надто коротке для нудних рішень!",
    "Ні - можливо, краще не ризикувати і обрати більш безпечний шлях.",
    "Так - давайте втілимо цю безумну ідею в життя!",
    "Ні - мабуть, це краще залишити на той випадок, якщо стане дуже нудно.",
    "Так - вперед до пригод!",
    "Ні - можливо, краще трохи розгубити голову, перш ніж вирішувати це.",
  ],
  en: [
    "Yes - let's dive into this silly adventure!",
    "No - maybe better leave it for another time.",
    "Yes - why not? Just kidding, let's take the risk!",
    "No - seems like it might lead to funny troubles.",
    "Yes - a good choice, as life's too short for boring decisions!",
    "No - maybe better not to risk and choose a safer path.",
    "Yes - let's bring this crazy idea to life!",
    "No - perhaps it's better to keep it for when it gets really boring.",
    "Yes - onwards to the adventure!",
    "No - maybe better to scratch our heads a bit before deciding this.",
  ],
  pl: [
    "Tak - zanurzmy się w tę głupią przygodę!",
    "Nie - może lepiej zostawić to na inny raz.",
    "Tak - dlaczego nie? Tylko żartuję, zaryzykujmy!",
    "Nie - wydaje się, że może to prowadzić do śmiesznych kłopotów.",
    "Tak - dobry wybór, ponieważ życie jest zbyt krótkie, aby podejmować nudne decyzje!",
    "Nie - może lepiej nie ryzykować i wybrać bezpieczniejszą ścieżkę.",
    "Tak - przynieśmy to szalone pomysł do życia!",
    "Nie - być może lepiej zostawić to na taki przypadek, gdy stanie się naprawdę nudno.",
    "Tak - w drogę do przygody!",
    "Nie - może lepiej pokręcić trochę głową, zanim zdecydujemy o tym.",
  ],
  ja: [
    "はい - このバカげた冒険に飛び込みましょう！",
    "いいえ - もしかしたら別の時にそれを残すのがいいかもしれません。",
    "はい - なぜだめなの？冗談です、リスクを取りましょう！",
    "いいえ - それはおかしなトラブルにつながるかもしれません。",
    "はい - いい選択です、人生はつまらない決定をするのには短すぎます！",
    "いいえ - リスクを冒すよりも安全な道を選ぶ方が良いかもしれません。",
    "はい - このクレイジーなアイデアを実現しましょう！",
    "いいえ - 本当に退屈になったときのためにそれを保持した方が良いかもしれません。",
    "はい - 冒険に向けて前進！",
    "いいえ - このことを決める前に少し頭をかき回した方が良いかもしれません。",
  ],
};
export const initialText = {
  uk: "Ваше запитання",
  en: "Your question",
  pl: "Twoje pytanie",
  ja: "あなたの質問",
};
